src/At21/EBoxOfficeBundle/Form/PlayType.php
<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 16/01/15
 * Time: 18:42
 */

namespace At21\EBoxOfficeBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class PlayType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fromDate', 'datetime', array(
                'format' => 'yyyy-MM-dd',
                'widget' => 'single_text',
                'html5' => true,
            ))
            ->add('toDate', 'datetime', array(
                'format' => 'yyyy-MM-dd',
                'widget' => 'single_text',
                'html5' => true,
            ))
            ->add('title', 'text')
            ->add('description', 'textarea')
            ->add('save', 'submit')
        ;
    }

    public function getName()
    {
        return 'play';
    }
}

src/At21/EBoxOfficeBundle/Resources/views/Admin/index.html.twig
{% extends "::base.html.twig" %}

{% trans_default_domain 'At21EBoxOfficeBundle' %}

{% block body %}
    <div class="ten wide column">
        <div class="ui grid">
            <div class="sixteen wide column">
                <a class="ui button" href="{{ path('at21_eboxoffice_play_new') }}">{{ 'admin.index.play.new.link'|trans }}</a>
            </div>
            <div class="sixteen wide column">
                <table class="ui very basic table">
                    <thead>
                        <th>{{ 'admin.index.play.table.headers.id'|trans }}</th>
                        <th>{{ 'admin.index.play.table.headers.fromDate'|trans }}</th>
                        <th>{{ 'admin.index.play.table.headers.toDate'|trans }}</th>
                        <th>{{ 'admin.index.play.table.headers.title'|trans }}</th>
                        <th colspan="1"></th>
                    </thead>
                    {% for play in plays %}
                        <tr>
                            <td>{{ play.id }}</td>
                            <td>{{ play.fromDate|date('Y-m-d') }}</td>
                            <td>{{ play.toDate|date('Y-m-d') }}</td>
                            <td>{{ play.title }}</td>
                            <td class="right aligned">
                                <div class="ui dropdown">
                                    {{ 'admin.index.play.action'|trans }}
                                    <i class="dropdown icon"></i>
                                    <div class="menu">
                                        <a href="{{ path('at21_eboxoffice_play_update', {'id': play.id}) }}" class="item">{{ 'admin.index.play.update.link'|trans }}</a>
                                        <a href="{{ path('at21_eboxoffice_play_check', {'id': play.id}) }}" class="item">{{ 'admin.index.play.check.link'|trans }}</a>
                                        <div class="divider"></div>
                                        <a href="{{ path('at21_eboxoffice_play_delete', {'id': play.id}) }}" class="item">{{ 'admin.index.play.delete.link'|trans }}</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="six wide column">
        <div class="ui grid">
            <div class="sixteen wide column">
                <a class="ui button" href="{{ path('at21_eboxoffice_theatre_new') }}">{{ 'admin.index.theatre.new.link'|trans }}</a>
            </div>
            <div class="sixteen wide column">
                <table class="ui very basic table">
                    <thead>
                        <th>{{ 'admin.index.theatre.table.headers.id'|trans }}</th>
                        <th>{{ 'admin.index.theatre.table.headers.name'|trans }}</th>
                        <th>{{ 'admin.index.theatre.table.headers.capacity'|trans }}</th>
                        <th colspan="1"></th>
                    </thead>
                    {% for theatre in theatres %}
                        <tr>
                            <td>{{ theatre.id }}</td>
                            <td>{{ theatre.name }}</td>
                            <td>{{ theatre.numberOfRows * theatre.numberOfSeatsPerRow }}</td>
                            <td class="right aligned">
                                <div class="ui dropdown">
                                    {{ 'admin.index.play.action'|trans }}
                                    <i class="dropdown icon"></i>
                                    <div class="menu">
                                        <a href="{{ path('at21_eboxoffice_theatre_update', {'id': theatre.id}) }}" class="item">{{ 'admin.index.theatre.update.link'|trans }}</a>
                                        <div class="divider"></div>
                                        <a href="{{ path('at21_eboxoffice_theatre_delete', {'id': theatre.id}) }}" class="disabled item">{{ 'admin.index.theatre.delete.link'|trans }}</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/At21/EBoxOfficeBundle/Resources/views/Admin/newTheatre.html.twig
{% extends "::base.html.twig" %}

{% trans_default_domain 'At21EBoxOfficeBundle' %}

{% block body %}
    <div class="sixteen wide column">
        <form class="ui form" action="{{ path('at21_eboxoffice_admin_new_event') }}" {{ form_enctype(form) }} method="POST" class="fos_user_profile_edit">
            <h4 class="ui dividing header">New Event</h4>
            <div class="four fields">
                <div class="ui input field">
                    {{ form_label(form.date) }}
                    {{ form_widget(form.date) }}
                </div>
                <div class="ui input field">
                    {{ form_label(form.title) }}
                    {{ form_widget(form.title) }}
                </div>
                {{ form_widget(form._token) }}
            </div>
            <div>
                <input class="ui submit button" type="submit" value="{{ 'admin.new_event.submit'|trans }}" />
            </div>
        </form>
    </div>
{% endblock %}